/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safehomejf;

/**
 *
 * @author Benedict
 */
public class Advanced extends javax.swing.JFrame {

    /**
     * Creates new form Advanced
     */
    public Advanced() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SHAccountIconLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ADinning = new javax.swing.JRadioButton();
        AFamily = new javax.swing.JRadioButton();
        AKitchen = new javax.swing.JRadioButton();
        ALinen = new javax.swing.JRadioButton();
        ALiving = new javax.swing.JRadioButton();
        AEntry = new javax.swing.JRadioButton();
        APorch = new javax.swing.JRadioButton();
        ALaundry = new javax.swing.JRadioButton();
        ABed1 = new javax.swing.JRadioButton();
        ABed2 = new javax.swing.JRadioButton();
        ABed3 = new javax.swing.JRadioButton();
        AMaster1 = new javax.swing.JRadioButton();
        AMaster2 = new javax.swing.JRadioButton();
        ALibrary = new javax.swing.JRadioButton();
        AGarage = new javax.swing.JRadioButton();
        ASelect = new javax.swing.JButton();
        ACancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setResizable(false);

        SHAccountIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Benedict\\Desktop\\Clayton State Spring 2016\\Software Engineering Design\\UI\\SafeHomeText.png")); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/Advanced.png"))); // NOI18N

        ADinning.setSelected(true);
        ADinning.setText("Dinnig");
        ADinning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADinningActionPerformed(evt);
            }
        });

        AFamily.setText("Family");
        AFamily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AFamilyActionPerformed(evt);
            }
        });

        AKitchen.setText("Kitchen");
        AKitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AKitchenActionPerformed(evt);
            }
        });

        ALinen.setText("Linen");
        ALinen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALinenActionPerformed(evt);
            }
        });

        ALiving.setText("Living");
        ALiving.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALivingActionPerformed(evt);
            }
        });

        AEntry.setText("Entry");
        AEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AEntryActionPerformed(evt);
            }
        });

        APorch.setText("Porch");
        APorch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APorchActionPerformed(evt);
            }
        });

        ALaundry.setText("Laundry");
        ALaundry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALaundryActionPerformed(evt);
            }
        });

        ABed1.setText("Bed Room 1");
        ABed1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABed1ActionPerformed(evt);
            }
        });

        ABed2.setText("Bed Room 2");
        ABed2.setToolTipText("");
        ABed2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABed2ActionPerformed(evt);
            }
        });

        ABed3.setText("Bed Room 3");
        ABed3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABed3ActionPerformed(evt);
            }
        });

        AMaster1.setText("Master Bed Room 1");
        AMaster1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMaster1ActionPerformed(evt);
            }
        });

        AMaster2.setText("Master Bed Room 2");
        AMaster2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMaster2ActionPerformed(evt);
            }
        });

        ALibrary.setText("Library");
        ALibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALibraryActionPerformed(evt);
            }
        });

        AGarage.setText("Garadge");
        AGarage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGarageActionPerformed(evt);
            }
        });

        ASelect.setText("SELECT");
        ASelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ASelectMouseClicked(evt);
            }
        });

        ACancel.setText("BACK");
        ACancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SHAccountIconLabel)
                .addGap(181, 181, 181))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ADinning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AMaster1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ALiving)
                            .addComponent(AEntry)
                            .addComponent(APorch)
                            .addComponent(ALaundry)
                            .addComponent(ABed1)
                            .addComponent(ABed2)
                            .addComponent(ABed3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AKitchen)
                                .addGap(18, 18, 18)
                                .addComponent(ALibrary))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ALinen)
                                .addGap(28, 28, 28)
                                .addComponent(AGarage))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AFamily)
                                .addGap(24, 24, 24)
                                .addComponent(AMaster2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ASelect)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ACancel)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SHAccountIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ADinning)
                            .addComponent(AMaster1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AFamily)
                            .addComponent(AMaster2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AKitchen)
                            .addComponent(ALibrary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ALinen)
                            .addComponent(AGarage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ALiving)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AEntry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(APorch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ALaundry)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ABed1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ABed2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ABed3)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ASelect)
                            .addComponent(ACancel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADinningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADinningActionPerformed
       if (ADinning.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
      
    }//GEN-LAST:event_ADinningActionPerformed

    private void AFamilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AFamilyActionPerformed
         if (AFamily.isSelected())
      ADinning.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_AFamilyActionPerformed

    private void AKitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AKitchenActionPerformed
        if (AKitchen.isSelected())
      AFamily.setSelected(false);
      ADinning.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_AKitchenActionPerformed

    private void ALinenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALinenActionPerformed
       if (ALinen.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ADinning.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_ALinenActionPerformed

    private void ALivingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALivingActionPerformed
         if (ALiving.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ADinning.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_ALivingActionPerformed

    private void AEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AEntryActionPerformed
      if (AEntry.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      ADinning.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_AEntryActionPerformed

    private void APorchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APorchActionPerformed
        if (APorch.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      ADinning.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);    }//GEN-LAST:event_APorchActionPerformed

    private void ALaundryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALaundryActionPerformed
         if (ALaundry.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ADinning.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_ALaundryActionPerformed

    private void ABed1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABed1ActionPerformed
         if (ABed1.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ADinning.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_ABed1ActionPerformed

    private void ABed2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABed2ActionPerformed
         if (ABed2.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ADinning.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_ABed2ActionPerformed

    private void ABed3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABed3ActionPerformed
         if (ABed3.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ADinning.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_ABed3ActionPerformed

    private void AMaster1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMaster1ActionPerformed
      if (AMaster1.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      ADinning.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_AMaster1ActionPerformed

    private void AMaster2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMaster2ActionPerformed
         if (AMaster2.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      ADinning.setSelected(false);
      AGarage.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_AMaster2ActionPerformed

    private void ALibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALibraryActionPerformed
         if (ALibrary.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      AGarage.setSelected(false);
      ADinning.setSelected(false);
    }//GEN-LAST:event_ALibraryActionPerformed

    private void AGarageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGarageActionPerformed
         if (AGarage.isSelected())
      AFamily.setSelected(false);
      AKitchen.setSelected(false);
      ALiving.setSelected(false);
      ALinen.setSelected(false);
      AEntry.setSelected(false);
      APorch.setSelected(false);
      ALaundry.setSelected(false);
      ABed1.setSelected(false);
      ABed2.setSelected(false);
      ABed3.setSelected(false);
      AMaster1.setSelected(false);
      AMaster2.setSelected(false);
      ADinning.setSelected(false);
      ALibrary.setSelected(false);
    }//GEN-LAST:event_AGarageActionPerformed

    private void ACancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACancelActionPerformed
        this.setVisible(false);
        new Interface().setVisible(true);
    }//GEN-LAST:event_ACancelActionPerformed

    private void ASelectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ASelectMouseClicked
       if (AGarage.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
             
       }
            if (AFamily.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
            }
            if (AKitchen.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
            }
        if (ALiving.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
        }
         if (ALinen.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
          if (AEntry.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
           if (APorch.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
            if (ALaundry.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
             if (ABed1.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
              if (ABed2.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
               if (ABed3.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
                if (AMaster1.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
                 if (AMaster2.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
                  if (ADinning.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
                   if (ALibrary.isSelected()){
           this.setVisible(false);
        new ALiving().setVisible(true);
    }
    }//GEN-LAST:event_ASelectMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Advanced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Advanced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Advanced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Advanced.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Advanced().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ABed1;
    private javax.swing.JRadioButton ABed2;
    private javax.swing.JRadioButton ABed3;
    private javax.swing.JButton ACancel;
    private javax.swing.JRadioButton ADinning;
    private javax.swing.JRadioButton AEntry;
    private javax.swing.JRadioButton AFamily;
    private javax.swing.JRadioButton AGarage;
    private javax.swing.JRadioButton AKitchen;
    private javax.swing.JRadioButton ALaundry;
    private javax.swing.JRadioButton ALibrary;
    private javax.swing.JRadioButton ALinen;
    private javax.swing.JRadioButton ALiving;
    private javax.swing.JRadioButton AMaster1;
    private javax.swing.JRadioButton AMaster2;
    private javax.swing.JRadioButton APorch;
    private javax.swing.JButton ASelect;
    private javax.swing.JLabel SHAccountIconLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
