/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safehomejf;

import javax.swing.JLabel;

/**
 *
 * @author Benedict
 */
public class Basic extends javax.swing.JFrame {

    /**
     * Creates new form Basic
     */
    public Basic() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SHAccountIconLabel = new javax.swing.JLabel();
        BSecurityLabel = new javax.swing.JLabel();
        BGarageLabel = new javax.swing.JLabel();
        BCameraLabel = new javax.swing.JLabel();
        BThemostatLabel = new javax.swing.JLabel();
        BSecurityTextLabel = new javax.swing.JLabel();
        BGarageTextLabel = new javax.swing.JLabel();
        BCameraTextLabel = new javax.swing.JLabel();
        BThermostatTextLabel = new javax.swing.JLabel();
        BExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setResizable(false);

        SHAccountIconLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Benedict\\Desktop\\Clayton State Spring 2016\\Software Engineering Design\\UI\\SafeHomeText.png")); // NOI18N

        BSecurityLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/BSecurity.png"))); // NOI18N
        BSecurityLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BSecurityLabelMouseClicked(evt);
            }
        });

        BGarageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/Bgarage.png"))); // NOI18N
        BGarageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BGarageLabelMouseClicked(evt);
            }
        });

        BCameraLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/BCamera.png"))); // NOI18N
        BCameraLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCameraLabelMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BCameraLabelMouseReleased(evt);
            }
        });

        BThemostatLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/Bthermostat.png"))); // NOI18N
        BThemostatLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BThemostatLabelMouseClicked(evt);
            }
        });

        BSecurityTextLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BSecurityTextLabel.setText("Security System");
        BSecurityTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BSecurityTextLabelMouseClicked(evt);
            }
        });

        BGarageTextLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BGarageTextLabel.setText("Garage Door");
        BGarageTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BGarageTextLabelMouseClicked(evt);
            }
        });

        BCameraTextLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BCameraTextLabel.setText("Camera");
        BCameraTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCameraTextLabelMouseClicked(evt);
            }
        });

        BThermostatTextLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BThermostatTextLabel.setText("Thermostat");
        BThermostatTextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BThermostatTextLabelMouseClicked(evt);
            }
        });

        BExit.setText("EXIT");
        BExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addComponent(SHAccountIconLabel)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BSecurityTextLabel)
                                .addGap(99, 99, 99)
                                .addComponent(BGarageTextLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BSecurityLabel)
                                    .addComponent(BCameraLabel))
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BThemostatLabel)
                                    .addComponent(BGarageLabel)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(BCameraTextLabel)
                        .addGap(125, 125, 125)
                        .addComponent(BThermostatTextLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(BExit)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SHAccountIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BSecurityLabel)
                    .addComponent(BGarageLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BGarageTextLabel)
                    .addComponent(BSecurityTextLabel))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BCameraLabel)
                    .addComponent(BThemostatLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BThermostatTextLabel)
                    .addComponent(BCameraTextLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(BExit)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BExitActionPerformed
      this.setVisible(false);
            new Interface().setVisible(true);
            
    }//GEN-LAST:event_BExitActionPerformed

    private void BSecurityLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSecurityLabelMouseClicked
        this.setVisible(false);
        new SecuritySystem().setVisible(true);
    }//GEN-LAST:event_BSecurityLabelMouseClicked

    private void BGarageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGarageLabelMouseClicked
      this.setVisible(false);
        new GarageDoor().setVisible(true);
    }//GEN-LAST:event_BGarageLabelMouseClicked

    private void BCameraLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCameraLabelMouseClicked
     this.setVisible(false);
        new Camera().setVisible(true);
        
       
    }//GEN-LAST:event_BCameraLabelMouseClicked

    private void BThemostatLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BThemostatLabelMouseClicked
     this.setVisible(false);
        new Thermostat().setVisible(true);
    }//GEN-LAST:event_BThemostatLabelMouseClicked

    private void BSecurityTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BSecurityTextLabelMouseClicked
        this.setVisible(false);
        new SecuritySystem().setVisible(true);
    }//GEN-LAST:event_BSecurityTextLabelMouseClicked

    private void BGarageTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGarageTextLabelMouseClicked
       this.setVisible(false);
        new GarageDoor().setVisible(true);
    }//GEN-LAST:event_BGarageTextLabelMouseClicked

    private void BCameraTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCameraTextLabelMouseClicked
       this.setVisible(false);
        new Camera().setVisible(true);
    }//GEN-LAST:event_BCameraTextLabelMouseClicked

    private void BThermostatTextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BThermostatTextLabelMouseClicked
        this.setVisible(false);
        new Thermostat().setVisible(true);
    }//GEN-LAST:event_BThermostatTextLabelMouseClicked

    private void BCameraLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCameraLabelMouseReleased
        
       
        
         
        
    }//GEN-LAST:event_BCameraLabelMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Basic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Basic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BCameraLabel;
    private javax.swing.JLabel BCameraTextLabel;
    private javax.swing.JButton BExit;
    private javax.swing.JLabel BGarageLabel;
    private javax.swing.JLabel BGarageTextLabel;
    private javax.swing.JLabel BSecurityLabel;
    private javax.swing.JLabel BSecurityTextLabel;
    private javax.swing.JLabel BThemostatLabel;
    private javax.swing.JLabel BThermostatTextLabel;
    private javax.swing.JLabel SHAccountIconLabel;
    // End of variables declaration//GEN-END:variables
}
